#!/bin/sh

rm $FOAM_USER_APPBIN/lowmachSolver
rm $FOAM_USER_LIBBIN/lowmachLib

wclean mypdfs
wclean lowmachLib
wclean lowmachSolver
wclean myLiquids/myFunctions
wclean myLiquids/aC3H6O
wclean myLiquids/liquidMixture

wmake libso myLiquids/myFunctions
wmake libso myLiquids/aC3H6O
wmake libso myLiquids/liquidMixture
wmake libso mypdfs
wmake libso lowmachLib
wmake lowmachSolver
